jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: firebase-basic
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
      - name: Install firebase-basic dependencies
        run: npm ci
      - name: Install functions dependencies
        working-directory: ./functions
        run: npm ci
      - name: Lint firebase-basic
        run: npm run lint
      - name: Unit tests (Jest)
        run: npm test -- --passWithNoTests --coverage
      - name: Build Next.js app
        run: |
          npm run build
          npm run export
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            out/
            .next/
          retention-days: 1
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: ./firebase-basic
          build: npm run build
          start: npx next start -p 3000
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120